language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: react-clean
  skip_cleanup: true
notifications:
  email: false
